In [2]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import MinMaxScaler

In [61]:
list1 = [
    [1,2,3,4],
    [2,4,5,6],
    [2,7,9,2]
]

arr1 = np.array(list1)

print(arr1[:,0])

df = pd.DataFrame(list1, columns=['a', 'b', 'c', 'd'])

MMscaler = MinMaxScaler()
MMscaler.fit(df)
df_trans = MMscaler.transform(df)

df_trans = pd.DataFrame(df_trans, columns=['a', 'b', 'c', 'd'])
df_trans

df_temp = df_trans.head(1)

type(df_temp)

[1 2 2]


pandas.core.frame.DataFrame

In [4]:
arr2 = np.array([[1],[2],[3],[4]])
print(arr2)
arr2 = np.append(arr2, [[5],[6],[7],[8]], axis = 1)
arr2.T

[[1]
 [2]
 [3]
 [4]]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
df2 = pd.DataFrame(list1, columns=['a', 'b', 'c', 'd'])
lili = df2["a"].to_list()
lili

[1, 2, 3]

In [6]:
arr1 = np.array([[1]])
arr2 = np.array([[4]])
arr3 = np.array([[6]])

arr_total = arr1
arr_total = np.append(arr_total, arr2)
arr_total = np.append(arr_total, arr3)
arr_total

array([1, 4, 6])

In [66]:
df3 = pd.DataFrame(list1, columns=['a', 'b', 'c', 'd'])
print(df3['a'].unique())
df3_list = (df3['a'].unique()).tolist()
df3_list
# df4 = pd.DataFrame(df3['a'].unique(), columns=['z'])
# df4

[1 2]


[1, 2]

In [18]:
list2 = [2,4,6,8]
df5 = pd.DataFrame(list2, columns = ['aa'])
df5

aa
0   2
1   4
2   6
3   8

In [69]:
df6 = pd.DataFrame(list1, columns=['z', 'x', 'c', 'v'])
df6

z  x  c  v
0  1  2  3  4
1  2  4  5  6
2  2  7  9  2

In [30]:
list_daycount = []
for i in range(10):
        list_daycount.append("DAY%d" %(i+1))
type(len(list_daycount))

int

In [63]:
arr4 = np.full((2,4), -1)
arr4.shape[1]

4

In [71]:
temp = np.array(['a', 'b'])
temp.tolist()

['a', 'b']

In [72]:
df6 = pd.DataFrame(list1, columns=['z', 'x', 'c', 'v'])
df7 = pd.DataFrame(list1, columns=['a', 'b', 'q', 'w'])
cc = pd.concat([df6, df7], axis = 0)