In [2]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import MinMaxScaler

In [6]:
list1 = [
    [1,2,3,4],
    [2,4,5,6],
    [2,7,9,2]
]

arr1 = np.array(list1)

print(arr1[:,0])

df = pd.DataFrame(list1, columns=['a', 'b', 'c', 'd'])

MMscaler = MinMaxScaler()
MMscaler.fit(df)
df_trans = MMscaler.transform(df)

df_trans = pd.DataFrame(df_trans, columns=['a', 'b', 'c', 'd'])
df_trans

# df_temp = df_trans.head(1)

[1 2 2]


a    b         c    d
0  0.0  0.0  0.000000  0.5
1  1.0  0.4  0.333333  1.0
2  1.0  1.0  1.000000  0.0

In [4]:
arr2 = np.array([[1],[2],[3],[4]])
print(arr2)
arr2 = np.append(arr2, [[5],[6],[7],[8]], axis = 1)
arr2.T

[[1]
 [2]
 [3]
 [4]]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
df2 = pd.DataFrame(list1, columns=['a', 'b', 'c', 'd'])
lili = df2["a"].to_list()
lili

[1, 2, 2]

In [6]:
arr1 = np.array([[1]])
arr2 = np.array([[4]])
arr3 = np.array([[6]])

arr_total = arr1
arr_total = np.append(arr_total, arr2)
arr_total = np.append(arr_total, arr3)
arr_total

array([1, 4, 6])

In [7]:
df3 = pd.DataFrame(list1, columns=['a', 'b', 'c', 'd'])
print(df3['a'].unique())
df3_list = (df3['a'].unique()).tolist()
df3_list
# df4 = pd.DataFrame(df3['a'].unique(), columns=['z'])
# df4

[1 2]


[1, 2]

In [8]:
list2 = [2,4,6,8]
df5 = pd.DataFrame(list2, columns = ['aa'])
df5

aa
0   2
1   4
2   6
3   8

In [9]:
df6 = pd.DataFrame(list1, columns=['z', 'x', 'c', 'v'])
df6

z  x  c  v
0  1  2  3  4
1  2  4  5  6
2  2  7  9  2

In [10]:
list_daycount = []
for i in range(10):
        list_daycount.append("DAY%d" %(i+1))
type(len(list_daycount))

int

In [11]:
arr4 = np.full((2,4), -1)
arr4.shape[1]

4

In [12]:
temp = np.array(['a', 'b'])
temp.tolist()

['a', 'b']

In [13]:
df6 = pd.DataFrame(list1, columns=['z', 'x', 'c', 'v'])
df7 = pd.DataFrame(list1, columns=['a', 'b', 'q', 'w'])
cc = pd.concat([df6, df7], axis = 1)
cc

z  x  c  v  a  b  q  w
0  1  2  3  4  1  2  3  4
1  2  4  5  6  2  4  5  6
2  2  7  9  2  2  7  9  2

In [14]:
df_empty = pd.DataFrame()
df9 = pd.DataFrame(np.array([1,2,3,4]).T)
print(df9.T)
df10 = pd.DataFrame(np.array([2,3,4,5]).T)
df_n = pd.concat([df_empty, df9], axis = 1)
df_n = pd.concat([df_n, df10], axis = 1)
# print(df_empty)
print(df_n)

   0  1  2  3
0  1  2  3  4
   0  0
0  1  2
1  2  3
2  3  4
3  4  5


In [15]:
list(range(-7, 1))

[-7, -6, -5, -4, -3, -2, -1, 0]

In [16]:
differenceSequence = pd.DataFrame([], columns=["DIFF", "FRAUD_TODAY"])

first_sequence = pd.DataFrame({"DIFF": [33], "FRAUD_TODAY": [0]})
second_sequence = pd.DataFrame({"DIFF": [143], "FRAUD_TODAY": [1]})

differenceSequence = pd.concat([differenceSequence, first_sequence], axis=0)
differenceSequence = pd.concat([differenceSequence, second_sequence], axis=0)
differenceSequence

DIFF FRAUD_TODAY
0   33           0
0  143           1

In [17]:
aass = pd.DataFrame([1,2], columns=['a'])
aass

a
0  1
1  2

In [18]:
list3 = [
    ["a", 0, 1],
    ["b", 5, 0],
    ["c", 2, 0],
    ["d", 8, 1],
    ["e", 9, 1],
]

list3_df = pd.DataFrame(list3, columns=["name", "val1", "bool"])
print(list3_df)
list4_df = list3_df[["val1", "name"]]
list4_df

  name  val1  bool
0    a     0     1
1    b     5     0
2    c     2     0
3    d     8     1
4    e     9     1


val1 name
0     0    a
1     5    b
2     2    c
3     8    d
4     9    e

In [7]:
def AMTCount(data):
    amtCounted = pd.DataFrame([], columns=["CC_NUM", "AMT_COUNT"])
    amtCounted["AMT_COUNT"] = (data["CC_NUM"].to_frame()).value_counts()
    amtCounted["CC_NUM"] = (data["CC_NUM"].value_counts()).index
    amtCounted["CC_NUM"] = amtCounted["CC_NUM"].astype("int")
    amtCounted.reset_index(drop=True, inplace = True)
    amtCounted = amtCounted.sort_values(by=["CC_NUM"] ,ascending=True)
    return amtCounted
    
df_temp = pd.DataFrame({"CC_NUM": [2,2,2,3,3,4,4,4,4,4], "AMT":[1,6,8,7,8,4,3,6,9,10]})
df_result = AMTCount(df_temp)
df_result
print(type(df_result.loc[1, "CC_NUM"]))

<class 'numpy.int32'>


In [10]:
fuck = pd.Series([1])
fuck
if(fuck.item() == 1):
    print("asdf")

asdf
