In [2]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import MinMaxScaler

In [61]:
list1 = [
    [1,2,3,4],
    [2,4,5,6],
    [2,7,9,2]
]

arr1 = np.array(list1)

print(arr1[:,0])

df = pd.DataFrame(list1, columns=['a', 'b', 'c', 'd'])

MMscaler = MinMaxScaler()
MMscaler.fit(df)
df_trans = MMscaler.transform(df)

df_trans = pd.DataFrame(df_trans, columns=['a', 'b', 'c', 'd'])
df_trans

df_temp = df_trans.head(1)

type(df_temp)

[1 2 2]


pandas.core.frame.DataFrame

In [4]:
arr2 = np.array([[1],[2],[3],[4]])
print(arr2)
arr2 = np.append(arr2, [[5],[6],[7],[8]], axis = 1)
arr2.T

[[1]
 [2]
 [3]
 [4]]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
df2 = pd.DataFrame(list1, columns=['a', 'b', 'c', 'd'])
lili = df2["a"].to_list()
lili

[1, 2, 3]

In [6]:
arr1 = np.array([[1]])
arr2 = np.array([[4]])
arr3 = np.array([[6]])

arr_total = arr1
arr_total = np.append(arr_total, arr2)
arr_total = np.append(arr_total, arr3)
arr_total

array([1, 4, 6])

In [66]:
df3 = pd.DataFrame(list1, columns=['a', 'b', 'c', 'd'])
print(df3['a'].unique())
df3_list = (df3['a'].unique()).tolist()
df3_list
# df4 = pd.DataFrame(df3['a'].unique(), columns=['z'])
# df4

[1 2]


[1, 2]

In [18]:
list2 = [2,4,6,8]
df5 = pd.DataFrame(list2, columns = ['aa'])
df5

aa
0   2
1   4
2   6
3   8

In [69]:
df6 = pd.DataFrame(list1, columns=['z', 'x', 'c', 'v'])
df6

z  x  c  v
0  1  2  3  4
1  2  4  5  6
2  2  7  9  2

In [30]:
list_daycount = []
for i in range(10):
        list_daycount.append("DAY%d" %(i+1))
type(len(list_daycount))

int

In [63]:
arr4 = np.full((2,4), -1)
arr4.shape[1]

4

In [71]:
temp = np.array(['a', 'b'])
temp.tolist()

['a', 'b']

In [74]:
df6 = pd.DataFrame(list1, columns=['z', 'x', 'c', 'v'])
df7 = pd.DataFrame(list1, columns=['a', 'b', 'q', 'w'])
cc = pd.concat([df6, df7], axis = 0)
cc

z    x    c    v    a    b    q    w
0  1.0  2.0  3.0  4.0  NaN  NaN  NaN  NaN
1  2.0  4.0  5.0  6.0  NaN  NaN  NaN  NaN
2  2.0  7.0  9.0  2.0  NaN  NaN  NaN  NaN
0  NaN  NaN  NaN  NaN  1.0  2.0  3.0  4.0
1  NaN  NaN  NaN  NaN  2.0  4.0  5.0  6.0
2  NaN  NaN  NaN  NaN  2.0  7.0  9.0  2.0

In [92]:
df_empty = pd.DataFrame()
df9 = pd.DataFrame(np.array([1,2,3,4]).T)
print(df9.T)
df10 = pd.DataFrame(np.array([2,3,4,5]).T)
df_n = pd.concat([df_empty, df9], axis = 1)
df_n = pd.concat([df_n, df10], axis = 1)
# print(df_empty)
print(df_n)

   0  1  2  3
0  1  2  3  4
   0  0
0  1  2
1  2  3
2  3  4
3  4  5


In [97]:
list(range(-7, 1))

[-7, -6, -5, -4, -3, -2, -1, 0]

In [112]:
differenceSequence = pd.DataFrame([], columns=["DIFF", "FRAUD_TODAY"])

first_sequence = pd.DataFrame({"DIFF": [33], "FRAUD_TODAY": [0]})
second_sequence = pd.DataFrame({"DIFF": [143], "FRAUD_TODAY": [1]})

differenceSequence = pd.concat([differenceSequence, first_sequence], axis=0)
differenceSequence = pd.concat([differenceSequence, second_sequence], axis=0)
differenceSequence

DIFF FRAUD_TODAY
0   33           0
0  143           1